### ISSUE TITLE
Add warning for "!!llTextBox!!" llDialog button labels

### ISSUE THREAD

**Issue by buildersbrewery** [Makopo/lslint#44]
Add warning for `"!!llTextBox!!"` llDialog button labels.

Compare:

<http://wiki.secondlife.com/wiki/LlDialog#Caveats>, subsection "button_limits"

**Comment by Sei-Lisa** [comment]
It doesn't make sense to do this. If you include that exact text as a constant in a button, you surely know what you're doing, and you don't need a warning for it. If it's the result of user input, lslint can't detect it anyway, because that can only be detected at runtime. Warning at every dialog that doesn't have constant arguments, just in case it somehow comes from the user, is an annoyance that will do more harm than good.
